INSERT INTO SELL_CATEGORY (SELL_CATEGORY_ID, SELL_CATEGORY_NAME) VALUES (1, '의류');
INSERT INTO SELL_CATEGORY (SELL_CATEGORY_ID, SELL_CATEGORY_NAME) VALUES (2, '가구');
INSERT INTO SELL_CATEGORY (SELL_CATEGORY_ID, SELL_CATEGORY_NAME) VALUES (3, '인테리어');
INSERT INTO SELL_CATEGORY (SELL_CATEGORY_ID, SELL_CATEGORY_NAME) VALUES (4, '소품');
INSERT INTO SELL_CATEGORY (SELL_CATEGORY_ID, SELL_CATEGORY_NAME) VALUES (5, '기타');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (1, 'cloth');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (2, 'wood');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (3, 'plastic');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (4, 'steel');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (5, 'glass');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (6, 'etc');
--