INSERT INTO SELL_CATEGORY (SELL_CATEGORY_ID, SELL_CATEGORY_NAME) VALUES (1, '의류');
INSERT INTO SELL_CATEGORY (SELL_CATEGORY_ID, SELL_CATEGORY_NAME) VALUES (2, '가구');
INSERT INTO SELL_CATEGORY (SELL_CATEGORY_ID, SELL_CATEGORY_NAME) VALUES (3, '인테리어');
INSERT INTO SELL_CATEGORY (SELL_CATEGORY_ID, SELL_CATEGORY_NAME) VALUES (4, '소품');
INSERT INTO SELL_CATEGORY (SELL_CATEGORY_ID, SELL_CATEGORY_NAME) VALUES (5, '기타');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (1, '천');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (2, '목재');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (3, '플라스틱');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (4, '철제');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (5, '유리');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (6, '기타');
--