INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (1, '천');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (2, '목재');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (3, '플라스틱');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (4, '철재');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (5, '유리');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (6, '기타');